language: python
python:
- '2.6'
- '2.7'
install: pip install -r requirements-test.txt
script: py.test
before_deploy: ./prepare-build.sh
deploy:
  provider: pypi
  user: bigpanda
  password:
    secure: DospQYpYTXBBdMpEEL01OL8idqNQfyevkmmCckKwpDMrzfavshuCGmjeuGcERFpKxZX+bv4vg9Ngt9HfCKiwU+0GbTBlLvL8cOD9yu3r3RWBpY06JNN12XwY6/P14mm0zmpFfwBnN04723eMyEhg/a4BZaKItcUZso13x5haJcI=
  on:
    tags: true
    all_branches: true
    repo: bigpandaio/bigpanda-splunk
