language: python
python:
- '2.6'
- '2.7'
install: pip install -r requirements-test.txt
script: py.test
before_deploy:
 - echo "**** $TRAVIS_BRANCH ****"
 - ./prepare-build.sh
deploy:
  provider: pypi
  user: bigpanda
  password:
    secure: bgSnTkRQYiZl5TGuE/mp2kj++vx3vAQAUZf0ZERfzvNR5dultKuegiBMOkcI9ZCNT2ooLaJURKdL4JA5Ip4qe5jBMtyTMDhlc/1+Ku+L/2IDT8lsyv9H9JhSjXcxoI72x9ZRAhD2TlXfuO1ZDp8ZAsB4DsN8XH0+SWM6XR3mhEU=
  on:
    tags: true
    repo: bigpandaio/bigpanda-splunk
